### ISSUE TITLE
Options->Controls and "Missing ... in l10n_en.XML"

### ISSUE THREAD

**Issue by DeckerMMIV** [netjungle/courseplay#30]
The 3 input-bindings; CP_Hud, CP_Modifier_1 and CP_Modifier_2, has no corresponding &lt;l10&gt;&lt;text&gt; entry.

So when going into [FS13] Options->Controls, it will display "Missing ... in l10n_en.XML", which does not look so good, IMHO.

**Comment by Satissis** [comment]
I took the liberty to add a picture of it ;)
![Picture of missing text](http://img.satis.dk/courceplay/cp_missing_key_text.png)

**Comment by JakobTischler** [comment]
God, I totally missed these issues, sorry for that.

I fixed the missing l10n, will be pushed in one of the next days.
