### ISSUE TITLE
Wont find combine automatic

### ISSUE THREAD

**Issue by Satissis** [netjungle/courseplay#32]
When combine mode is set and a combine is harvesting, it wont find that combine automatic when the Find Combine is set to automatic search, as the picture is showing down below:
![can't find combine](http://img.satis.dk/courceplay/cp_find_combine_automatic_search.png)

As you can see there is a combine close to it.

If I set the Find Combine to Manuel and chose the combine, it works.

Kind regards
Satis

**Comment by JakobTischler** [comment]
It can only find the combine if and when both the tractor and the combine are on the same field. If the tractor is, e.g., on a road right beside the field that the combine is on, it won't find it in automatic mode.
