### ISSUE TITLE
Combine tractor stuck when trying to empty combine

### ISSUE THREAD

**Issue by Satissis** [netjungle/courseplay#33]
When using the old Fahr M66 combine, the tractor get stuck in traffic if the combine is holding still and sometimes also when trying to run beside it.
Here is a picture with a highlighted marking:
![Stuck in traffic](http://img.satis.dk/courceplay/cp_side_offset_automatic_stuck_in_traffic.png)

As you can see the side offset is set to auto and it's automatic set to 3.3m
If I use a newer combine with a whiter cutter, the problem is almost gone, but it still happens some times.

If I set the Side Offset to manuel 4.3m the problem is gone on Fahr M66 model and also on the newer models if I give it around 0.5 to 1 m + in manuel from what the auto set it to.
Here is another picture of it working with manuel:
![Manuel Side Offset](http://img.satis.dk/courceplay/cp_side_offset_manuel.png)

When setting it to manuel the side offset doesn't look as nice when it drive beside it, but it's working.

Kind regards
Satis

**Comment by bioxz** [comment]
Same problem here. While driving to the combine the tractor gets stuck behind it. Also it often stops beside the combine at the end of a lane with the info "Combine is telling me to stop".

**Comment by JakobTischler** [comment]
Yeah this is a known issue so far. The problem occurs more often the smaller the cutter is. Honestly, I haven't found a perfect solution yet that would work all the time with all the combines. Will keep you posted.

**Comment by Satissis** [comment]
I actually found out what was causing this.
I was working on a mod and when I turned on developer mode for FS and lookes at the collition boxes, I notised that the trafic colition box is so high that it hits the tip of the combine pipe collotion.
Is it possible to set the pipe collition to be ignores untill the tracktor have passed it since that would actually solve this :)

Kind regards
Satis

**Comment by JakobTischler** [comment]
Sounds like a reasonable idea. I'll pass it on. Thanks.

**Comment by hansi123** [comment]
Has the solution to this issue been found?

btw, thank you very much developers for using your time on this incredible mod

**Comment by JakobTischler** [comment]
Since the problem _only_ occurs with much smaller combines like the Fahr, we can't really make an exception in the offset algorithm - for now at least. Suggested solution is indeed to use the manual offset.

**Comment by Satissis** [comment]
What about the suggestion on the ignore the collision box I posted above. Was that not able to do ?

Kind regards
Satis

**Comment by ThomasGaertner** [comment]
unfortunately we are only able to ignore the complete collision and not single boxes, so it's too dangerous to ignore the complete combines on the field
