### ISSUE TITLE
Wont refill trailers at silos

### ISSUE THREAD

**Issue by Satissis** [netjungle/courseplay#34]
When making a sell run where a tractor and a trailer should drive in drivinghelper and drive under the silo to fill the trailer and drive to a sell point to unload the trailer and the return again, to do the same over and over again, the tractor stops before the trailer is under the unloading point and the trailer wont get fillet up.

Here is how I did the setup:
In the picture below you can see how I have positioned the tractor and trailer when I pressed start recording:
![Position at start recording](http://img.satis.dk/courceplay/cp_sell_run_record.png)

I then drive to the sell point and unload. Drive back and stopped right before the silo and pressed stop recording so the start and stop don't overlap.
Now I manuel refill the trailer and press start driving.
Tractor drives to sell point and unload and drives back again to the silo and under it but stops before the trailer gets under the refilling point, just as the picture shows below:
![Wrong refill point](http://img.satis.dk/courceplay/cp_sell_run_loading.png)

Kind regards
Satis

**Comment by Satissis** [comment]
I found this on line 28 in mode1.lua:

``` lua
--if self.loaded ~= true and ((self.recordnumber == 2 and tipper_fill_level < tipper_capacity and self.unloaded == false and self.dist < 10) or self.lastTrailerToFillDistance) then
```

and this on line 29:

``` lua
  if self.loaded ~= true and ((self.recordnumber == 2 and tipper_fill_level < tipper_capacity and self.unloaded == false ) or self.lastTrailerToFillDistance) then
```

If I comment out line 29 and remove the comment signs on line 28 it's working again at some points. What I mean by that is that if you only use 1 or 2 tippers, it will work okay, but if you have more that that, it will not fill tipper nr. 2 and get stuck there.

Just a side note to help you guys ;)

**Comment by JakobTischler** [comment]
Satissis, please check with the latest version. Should be fixed now (https://github.com/netjungle/courseplay/commit/13645598502fa32d8e7d112ee9d183dd9ca5d42f)
