### ISSUE TITLE
Log error when trying to run the courseplay from github

### ISSUE THREAD

**Issue by Maon** [netjungle/courseplay#36]
Hi everyone,

maybe I do something wrong, but I had following message in the log:
Error: LUA running function 'loadMapFinished'
C:/Users/Ondra/Disk Google/My Games/FarmingSimulator2013/mods/zzz_courseplayn2/courseplay_manager.lua(34) : attempt to index global 'courseplay' (a nil value)

and game did not start

Thanks.
Ondra

**Comment by Satissis** [comment]
One thing I notised:
Your courseplay folder is named: zzz_courseplayn2 which wil make it not work at all. did that done that :)
it needs to be ZZZ_courseplay for the folder or ZZZ_courseplay.zip for the ziped file
