### ISSUE TITLE
bad turning. auto combine detection.

### ISSUE THREAD

**Issue by FS-UK-TheMan1988** [netjungle/courseplay#37]
when i do silage with the ingame krone im having issues with the trators turning it's like they dont know what side to choose. and gets stuck behind the forager.

for combines: if the combine gets unloaded at the end the tractor drives in the next line of crop and stops.
and the fill level or the detection of it does not work no matter what level i set it for. but this could also be a problem with the detection of the combine(i use large field) . using large fields is a problem for cp it's like the range is not good enough(dont know what else it could be)

and i would like(if possible) to see more futures like

CP for feeding and bedding

front loaders can load trailers(manure spreder. feeder etc) and empty biogas plant silos

sorry for bad english:)

danish.

**Comment by JakobTischler** [comment]
Sorry for the delayed answer, I'm getting no notifications for GitHub issues.

Check out our current feature changelog at http://www.modhoster.de/projects/courseplay/project_logs/4015#courseplay_20130121_english

Among other things, we've heavily improved the turning maneuver when unloading choppers. Will be pushed to github during the next couple of days.

**Comment by FS-UK-TheMan1988** [comment]
ok so its not released yet:)

**Comment by JakobTischler** [comment]
We're currently still testing a couple of options before pushing it to GitHub, which you could consider something between alpha and beta state. A public 'final' release is still way further away.

**Comment by JakobTischler** [comment]
With the newest files, please check again if the problem still exists on your end.

**Comment by JakobTischler** [comment]
No answer for a month -> closed.
