### ISSUE TITLE
Wendemnöver am Feldende

### ISSUE THREAD

**Issue by LAWI-Game** [netjungle/courseplay#38]
Habe fürs dreschen in den Zeilen 308, 387 und 564 die Abfrage
 "IF leftFruit > rightFruit then" in 
"IF ( leftFruit > rightFruit and not combine_turning ) or ( leftFruit < rightFruit and combine_turning ) then" geändert. 
Seitdem fährt der Abfahrer immer aus dem Getreide, selbst wenn der Mädrescher am Ende des Feldes steht.
Anscheinen wird bei Start Wendemanöver der Helferkurs Mädrescher direkt geändert und zeigt entgegen der Drescherichtung.

**Comment by JakobTischler** [comment]
The turn maneuvers have been reworked. Please check again with the newest files.

**Comment by ThomasGaertner** [comment]
fixed with "improved truning maneuver after unloading combine"
closed
