### ISSUE TITLE
Feeding troughs and fruit/fill types

### ISSUE THREAD

**Issue by TheCadde** [netjungle/courseplay#39]
I had to modify two files to be able to use the feeding troughs with forage wagons holding mown grass.

The fruit type returned from the forage wagon with grass in it is 7 but the feeding trough only has 12, 13, 20, 21 and 22 as acceptable filltypes. (They are grass_windrow, silage etc)

So the modifications i had to make where:

triggers.lua @ line 68:
`if trigger.acceptedFillTypes[fruitType] then`
... replace with ...
`if trigger.acceptedFillTypes[fruitType] or trigger.acceptedFillTypes[self.tippers[1].currentFillType] then`

tippers.lua @ line 193:
`if self.currentTipTrigger.acceptedFillTypes[fruitType] then`
... replace with ...
`if self.currentTipTrigger.acceptedFillTypes[fruitType] or self.currentTipTrigger.acceptedFillTypes[tipper.currentFillType] then`

I am sure you will have a better solution to the problem but it was the only way i could find without rewriting a lot more stuff.

This way feeding troughs who doesn't accept the grass fruit type will still be recognized as valid tipTriggers when hauling a forage wagon with grass in it.

**Comment by JakobTischler** [comment]
Thanks for the input. We haven't even had the chance of testing the automatic unloading into feeding troughs yet, so the problem hadn't occured to us yet.

I'll check it out ... later - where "later" is a rather loose term ;)

**Comment by abehnke** [comment]
This also fixes a mode 6 problem in that forager wagons drive past without tipping at the straw,grass,hay tipping location on the farm (the brown shed on west side).  I am using a zip file downloaded from github on Jan. 24, 2013.
