### ISSUE TITLE
Fieldwork, failure to turn implement back on after unload.

### ISSUE THREAD

**Issue by TheCadde** [netjungle/courseplay#40]
As a (in this case) a forage wagon becomes full or you set "drive now" or start and stop driving a field route. It sets abortWork to the current waypoint and drives to unload.
When it returns to the field it goes to the saved position abortWork - 4 to resume work but the forage wagon is not turned back on.

This is because the condition is never reached as it looks for abortWork - 2 but abortWork is reset to nil at abortWork - 4.
This small change fixes that issue:

mode6.lua @ line 97:
`if workArea and fill_level ~= 100 and (self.abortWork == nil and last_recordnumber == self.startWork or self.abortWork ~= nil and last_recordnumber == self.abortWork - 2) then`
needs to be replaced with...
`if workArea and fill_level ~= 100 and (self.abortWork == nil and last_recordnumber == self.startWork or self.abortWork ~= nil and last_recordnumber == self.abortWork - 4) then`

The change is the last number, changing it from -2 to -4 so it turns the machine back on before abortWork is nulled.

**Comment by JakobTischler** [comment]
Hm, interesting. A bug very similar to this one (or at least directly related) is actually in the bugtracker (https://www.pivotaltracker.com/projects/675867#). But maybe with you providing a solution this will be pushed forward even faster. Thanks.

**Comment by JakobTischler** [comment]
Since this is the same as #53 (or vice versa), I'll close this one down.
