### ISSUE TITLE
course generate direction control

### ISSUE THREAD

**Issue by abehnke** [netjungle/courseplay#41]
In the course generate function, it is possible to have it generate north-south patterns or east-west patterns. (Turn around in the north/south end of the field or east/west ). The direction of the course layout in the course generate function appears to be controlled by the average of the angles of the first 5 waypoints.  The angle is how the vehicle moves from waypoint to waypoint with 0 degrees due south, 90 is due east, -90 is due west both -180 and 180 are north.  The problem is that the code looks for angles as follows (in recordings.lua) : "if (duangel > 180 and duangel < 270) or (duangel > 0 and duangel < 90) then".  As an example, if you are starting from a SW corner, you can head north at any consistent angle also you can head slight north of due east and get the east-west pattern (turn around on the east and west ends) but if you head slightly south of due east then get the north-south pattern.  Maybe the conditional would work better if it was something like "if math.abs(duangel) > 45 and math.abs(duangel) < 135  then". Also it would be good to add some documentation to the readme file about how this works.

**Comment by JakobTischler** [comment]
The whole course generation algorithm is something we plan to ... change. Which could mean anything between "overhaul" and "destroy and rebuild". But, this is a damn huge task which has to prioritized lower than, e.g., fixing the current bugs and making the driving part less error prone.

Personally, I've written a new algorithm, actually a whole new system, outside of lua for course generation, and it works, let's say, 90% well. It includes the choosing of starting corner and direction. My plan is to convert it to lua at some point, and hence incorporate it in CP.
But until then this will have to make due. If you do have experience, especially good geometrical knowledge and stuff like that in addition to coding experience, we could always use a helping hand or two... :)

Concerning the documentation: ha, that's something else we "plan" on revamping, but as you can imagine that's not the easiest of challenges (workload-wise). As of right now, we have 2.5 active team members, and time is something becoming rather rare these days. But, again, it's on the to do list.

**Comment by JakobTischler** [comment]
Update: please see https://github.com/Courseplay/courseplay/commit/61dd98193ff2076b9c69b2cae2ef96b54bb7759e
