### ISSUE TITLE
side_to_drive - potato and beet

### ISSUE THREAD

**Issue by abehnke** [netjungle/courseplay#42]
The side_to_drive function uses Utils.getFruitArea.  This function does not appear to know about potatoes and beets. It reports zero amount for these fruit types.  Thus side_to_drive gives misleading info to the calling function. As a temporary work around, if these types are being harvested, I park the tractor+tipper on the 3rd waypoint. This works for me since I usually aim my unload course into the field.

**Comment by JakobTischler** [comment]
To be honest, I can't see the problem. side_to_drive is never being used with harvesters, only with choppers, and sometimes combines. In which situation do you say would it affect the harvesters?
Also, even side_to_drive's var equivalent 'self.sideToDrive' is ONLY being used with choppers.

Now, concerning getFruitArea not recognizing potatoes and sugarbeet - that's a whole other problem that we need to get fixed after the script documentation will be released.

**Comment by abehnke** [comment]
With regard to the potato and beet harvesters (Grimme Maxtron 620 and Grimme Tectron 415) and side_to_drive, I forgot to mention I am working with a zip file downloaded on Jan. 4, 2013 - so it is not your current updates. Sorry for the confusion.  In this older version of mode2.lua, at line 384, the side_to_drive function is used on these potato and beet harvestors.  I think the game refers to harvesters as combines even though a combine is a certain type of harvester.
