### ISSUE TITLE
tanker wont refill - fertilizer mode 4

### ISSUE THREAD

**Issue by abehnke** [netjungle/courseplay#43]
Sometimes when I attempt to use the Kotte GARANT Slurry Tanker with fertilizer mode, it fails to stop and fill at the tank by the biogas plant.  I sprinkled some "print" around in the code and narrowed it down to this "if" in drive.lua

if fill_level < self.required_fill_level_for_drive_on and not self.loaded and activeTool.sprayerFillTriggers ~= nil and table.getn(activeTool.sprayerFillTriggers) > 0 then

It appears that self.loaded is sometimes true and sometimes false.  I can usually get it false if I start a course just before the STOP sign. But starting from other places it ends up true and the tanker won't fill.  I could not quite understand what the purpose of self.loaded is here so I removed it. It worked OK on one limited test.

**Comment by JakobTischler** [comment]
So.... this is a tough one. In the team we've experienced two totally different results:
1) Thomas has had no problems at all with automatic refilling, opening the fertilizer machines etc.
2) Me, on the other hand, I got none of those things working, just like you.

So, different, non reproducable results are way worse than bad results.

I've played around with self.loaded, replacing it with "fill_level < 100", to no avail. For now I'm gonna have to push this one back. Unless YOU come up with an idea ;)

It's in the bug tracker now: https://www.pivotaltracker.com/story/show/43270565

**Comment by abehnke** [comment]
I did some debugging on this. I made a fertilize course on field 7 consisting of a generated pattern combined with a run to the biogas tank and back to the field. I did some test runs.

I put a print just before the following big "if" in drive.lua:

print(string.format("loaded: %s", self.loaded and "true" or "false"))
if fill_level < self.required_fill_level_for_drive_on and not self.loaded and activeTool.sprayerFillTriggers ~= nil and table.getn(activeTool.sprayerFillTriggers) > 0 then

I first edited the vehicle.xml file, and set AbortWork="nil" to clear out prior experiments. Now, if I do a clean run with no pressing the stop function or other interruptions then all goes OK. 

The following happens (as expected) when the tank goes empty:
1 drives to the end wait of the field
2 continues on the combined course to the biogas tank
3 refills
4 drives to the STOP sign
5 drives to the abort point and continues spraying

If instead, I interrupt the drive, by pressing stop drive, then immediately the self.loaded goes true.[EDIT actual it goes true on the next drive command]  If I drive around on manual and then attempt to continue the job then self.loaded stays true until the drive passes the STOP sign.  In detail:

The following happens when the tank goes empty with self.loaded = true:
1 drives to the end wait of the field
2 continues on the combined course to the biogas tank
3 drives past the refill since self.loaded is true so the big "if" is false
4 drives to the STOP sign - this causes self.loaded to be set to false.  I assume at this point it would just cycle around and eventually refill.

Except when the system starts in base.lua, the only place self.loaded gets set to false is near the comment "reset some variables" in drive.lua.

I am not sure how to fix this since I don't understand the purpose of self.loaded.  I might try more detailed experiments with self.loaded removed from the big "if".

I suppose I tripped over this problem because my spray pattern misses some parts of the field so when I would see this, I would press stop do some manual spraying then set it back on drive.

![biogas3](https://f.cloud.github.com/assets/3346683/100626/b319db9c-683c-11e2-8a09-cdc915327fb0.png)

**Comment by abehnke** [comment]
I have removed the "not self.loaded" from the "if" at line 268 in drive.lua to see what happens.  So far, seems OK provided I start the course with something in the sprayer tank.  I can interrupt the course at anytime, drive around and manual spray.  If I press start drive then it goes to the last place it was spraying. 

I did find one problem but it also happens using an unmodified ZZZ_courseplay (none of my debugging stuff). Also, since I was not certain if my current large fertilizer course was a problem - I erased my courseplay.xml and made a simpler fertilizer course.

If I start the course with an empty tank then the following happens:

From a starting point just before first waypoint:
1 drives to first waypoint which is also a crossing and wait waypoint
2 drives to second wait waypoint
3 drives the fill route to the tank
4 stop and refill
5 drives the fill route to the STOP sign 
-- all these steps are OK so far
6 just before the STOP sign lua throws an error for line 107 of drive.lua - attempt to index field '?' (a nil value)

Also an interesting thing, it makes use of the "Drive on at %" that is normally used to control the tippers.  If I set 10% then it starts leaving the tank area at 10%.  Not a bug - a feature! - handy for debugging since I don't have to wait for it to spray a full tank.

**Comment by JakobTischler** [comment]
I've been meddling with and testing the problem as well, and came to same conclusion: there's no need for `self.loaded` in mode 4.

Just to make sure - you mean line 107 of the current drive.lua online here - not the public release a couple of months ago, right? If so ... damn it! This would mean that at that moment, there's no current waypoint. Which, you can image, is a rather bad thing to happen. I'll look into it.

Thanks so far for the time and work you've put into this.

**Comment by JakobTischler** [comment]
Concerning the "it's a feature, not a bug thing"... yes and no. At first glance it seems nice to be able to set it - on the other hand, why would you ever not have it at 100%? What possible reason could one have not to fully fill the implement? You could be coming from mode 2, with the level set at 80% or so, and plain forget to set it to 100% each time you wanna fertilize something. So ... yeeeeah. 100% sounds better to me.

I will set this to `if fill_level < 100` for mode 4, and `if fill_level < self.required_fill_level_for_drive_on` for mode 8. Or might consistency be key here?

**Comment by abehnke** [comment]
> you mean line 107 of the current drive.lua online here

I am using a ZIP file that I downloaded from github on Jan. 24, 2013.

**Comment by JakobTischler** [comment]
Could you please test it again with the current (29 Jan 2013) version? It worked on my end, but I'd still like to see a couple more approvals on this.

**Comment by abehnke** [comment]
Sure, I will be happy to test this.  I downloaded from github a new zip file on Jan. 29, 2013.  I tested using a Deutz M620 and kotte/garantVTL19500 tanker at the biogas tank.

I set the fill level to 10%.

First test with an empty tanker resulted in the same error : FarmingSimulator2013/mods/ZZZ_courseplay/drive.lua(107) : attempt to index field '?' (a nil value)
Error: LUA running function 'update'.  Maybe this is scheduled for a future release?

Second test worked fine - here are the details:

Course is designed with two waits (defining the work area) and two crossings (start and stop)
-- manual steps
1 partially loaded the tanker
2 placed tanker at start point
3 press start drive
-- remaining steps are CP
4 sprayer unfolds
5 spray
6 tank goes empty so fold up
7 beeline to about the 3rd waypoint before the 2nd WAIT (end of work area)
8 drive fill up course
9 tanker fills up 100% 
10 returns to STOP
11 beeline to last spray point 
12 unfold and continue spray

All seems OK.  Thanks for fixing this.

**Comment by abehnke** [comment]
oops I pressed the Closed and Reopened buttons by mistake.  I thought close would close the window. Sorry about that.

**Comment by JakobTischler** [comment]
Great to hear. Two things though:
1) I can honestly say I have no clue yet why it would throw the drive 107 error when the tanker is empty. Not a single damn idea. I will have to a) run some tests to confirm this, and b) print the shit out of that whole process to see what is happening.
2) your steps 7 and 11: at which speed / speed level did the driver drive to those points? It used to be level one (turn maneuver speed), I changed it to level 2 (field work speed) but haven't yet had a chance to test if that actually worked.

**Comment by abehnke** [comment]
> at which speed / speed level did the driver drive to those points?

For the speed test, I set Turn = 5 kph, Field =  25 kph, Street = 50 kph. CP set to max speed rather than recorded speed. I downloaded a new zip from github.

Since I am in USA my speeds are in mph for the next part.

1 spraying speed - 12-16 mph
2 beeline to wait #2 waypoint - 27 mph
3 when within about 3 waypoints of wait #2 - 4 mph
4 wait #2 to tank - 32 mph
5 u turn behind tank - 15 mph
6 back to STOP sign - 30 mph
7 approach near STOP sign - 3-4 mph
8 beeline to resume spraying 30 mph

**Comment by JakobTischler** [comment]
First, thanks. I just realised the whole kph/mph conversion, or lack thereof, in the game is rather disturbing and/or confusing. Am I right to assume all Giants did was changing the "kph" string to "mph" and call it a day? Or do these speeds actually "feel right" to you (meaning, are they the correct speeds, in terms of mph)?

Now, the fact that the beelines (2 and 8) are approx. at field speed is good to hear. The fact that the spraying speed  isn't ... is not. There will be a new update for the speeds tomorrow, and it will make a rather, albeit not so obvious at first, clear difference if you're using max speed or recorded speed.

**Comment by abehnke** [comment]
About the mph vs kph, sorry for the confusion but I wanted to record the raw data as I see it on the screen without me making any math errors in converting the numbers.  Anyway, the tractor I am using - Deutz M620's maximum speed is around 32 mph (in the game).  If I want this speed in CP Target mode then I set a CP Street value of 52.  When I do most field work, I set a CP kph of 25.  This gives me 16 mph which is the max of most of the farm tools. The tractor was going at or near its maximum - Street speed - in steps 2,4,6,8.  It was properly doing Field speed while spraying.  I know this because if I switch to manual and attempt to go over 16 mph or 26 kph - I get the warning from FS13 and the tool stops working.

**Comment by Satissis** [comment]
I Have tried to change between german and english versions and they didn't just change the label but the speed number is different as well, like I drive 30Mph in the english version and around 40-50 km/h in the german version, so yeah there is a difference :)

Kind regards
Satis

**Comment by JakobTischler** [comment]
Good to know, thanks @Satissis. This means we might actually have to incorporate that at some point in the future (display the corresponding mph speed instead of kph). Does any of you know if there are different game version of en-us (North American market) and en-en/en-gb (UK market)? Meaning, which speed display do the British gamers use? Easiest for us would be if all game versions that use the "en" locale use mph.

Back to topic (@abehnke): the drive.lua 107 bug bothered me, so I tested the same situation you've described (with a fertilizer instead of liquid manure, shouldn't make a difference though). Only that it worked perfectly for me. When getting to the last point of the fill route, no error was thrown, instead it went on to the first wait point (start of the field course).
I will also test this with liquid manure, but I can't really see how or why it would throw an error.

In the meantime, could you please add the following lines  to drive lua, exactly _above_ line 107 (before `cx, cz = ...`)

``` lua
    --TODO: mode 4 debug (error when starting with an empty fertilizer tank)
    if self.ai_mode == 4 then
        if self.Waypoints ~= nil then
            print(string.format("drive %i: %s: #self.Waypoints=%s", debug.getinfo(1).currentline, self.name, tostring(#self.Waypoints)));
            print(string.format("drive %i: %s: self.Waypoints[%s]: cx=%s, cy=%s", debug.getinfo(1).currentline, self.name, tostring(self.recordnumber), tostring(self.Waypoints[self.recordnumber].cx), tostring(self.Waypoints[self.recordnumber].cz)));
        else
            print(string.format("drive %i: %s: self.Waypoints==nil", debug.getinfo(1).currentline, self.name));
        end;
    end;
```

**Comment by abehnke** [comment]
I did some more testing. Removed all mods except the latest CP download as of today Jan. 31, 2013.

All tests start with empty tank.

Test 1
Started a fresh game - savegame1 - but gave myself $6,000,000 and filled the liq. man. to 100,000 by editing xml. Turned off traffic.
Make a simple loop fert. course on fld 7 - result no error!

hmm - confusing

Test 2 
Copied my current savegame2 to savegame3 (a test area)
Ran my "fld 7 fert slur" course - result: throws error

Examined the courseplay.xml for the Test 1 and Test 2 and noticed that in Test 1 wp#1 had just "crossing set" and wp#2 had just "wait" set whereas my Test 2 course had both of these set on wp#1 plus neither set on wp#2.

I edited drive.lua to include the debugging code.

Test 3
Edited my "fld 7 fert slur" in courseplay.xml so that "crossing" is set on wp#1 and "wait" is set on wp#2.  Result: - no error!

Test 4
Edited my "fld 7 fert slur" in courseplay.xml so that "crossing" is set on wp#1 and "wait" is set on wp#1. Neither set on wp#2.  Result: error

---

log.txt at moment of error:

drive 111: Deutz Agrotron M620: #self.Waypoints=854
drive 112: Deutz Agrotron M620: self.Waypoints[854]: cx=376.93447875977, cy=-502.84030151367
drive 111: Deutz Agrotron M620: #self.Waypoints=854
drive 112: Deutz Agrotron M620: self.Waypoints[854]: cx=376.93447875977, cy=-502.84030151367
drive 111: Deutz Agrotron M620: #self.Waypoints=854
drive 112: Deutz Agrotron M620: self.Waypoints[854]: cx=376.93447875977, cy=-502.84030151367
drive 111: Deutz Agrotron M620: #self.Waypoints=854
drive 112: Deutz Agrotron M620: self.Waypoints[1]: cx=351.55087280273, cy=-399.98870849609
drive 111: Deutz Agrotron M620: #self.Waypoints=854
Error: LUA running function 'update'
C:/Users/abehnke/Documents/My Games/FarmingSimulator2013/mods/ZZZ_courseplay/drive.lua(112) : attempt to index field '?' (a nil value)
drive 111: Deutz Agrotron M620: #self.Waypoints=854
Error: LUA running function 'update'
C:/Users/abehnke/Documents/My Games/FarmingSimulator2013/mods/ZZZ_courseplay/drive.lua(112) : attempt to index field '?' (a nil value)
drive 111: Deutz Agrotron M620: #self.Waypoints=854
Error: LUA running function 'update'

---

Not sure how I got both "crossing" and "wait" set on the same wp#1 but I might have edited the XML sometime in the past.

**Comment by JakobTischler** [comment]
Aaaah, that actually explains a lot.
When generating a field course, both crossing points and wait points are set automatically (crossing="1" wait="1") and the first and last point of the course. When recording, you have to set the wait points manually, crossing points are still set automatically for the first and last waypoints. So the only reason I can see where you don't have them in your field course would be either some very weird error when recording/generating the course, or you did infact temper with the xml (which is fine of course, as long as you don't break anything ;-)).

When loading this array of courses (field course, course for refilling etc.) you will always have to make sure that you have exactly 2 waypoints, otherwise the apocalypse will apparently come down on you...

We might have to add some pre error checking before allowing the "drive" function to put the vehiicle into drive mode, for example more than or less than 2 wait points in modes 4 and 6.

**Comment by Satissis** [comment]
Jakob, I am almost sure that there is no difference's in the local english versions no matter if you are in UK or in USA. The reason for my conclusion on this is that I actually have the local files stored and there is only on english file for it, no en-en or en-gb or anything.
