### ISSUE TITLE
readme.txt

### ISSUE THREAD

**Issue by Goten87** [netjungle/courseplay#44]
can u make a english `readme.txt` to for the english and other people
call it `readme_en.txt`

**Comment by JakobTischler** [comment]
Is being done as we speak, meaning it's in progress. It'll just take some time. In the meantime - the update information stuff contains an English section as well now: see http://www.modhoster.de/projects/courseplay/project_logs/4015#courseplay_20130121_english

**Comment by Goten87** [comment]
well thats for as i know the change log not the `readme.txt` or will that come later on
