### ISSUE TITLE
Combi mode error

### ISSUE THREAD

**Issue by Goten87** [netjungle/courseplay#46]
when my tractor is moving away from the combine it parks infront it and get it all stuck
so i need to move it away manual and then it works again and need to start over the course again
![Stuck](https://f.cloud.github.com/assets/1938598/96605/c4eb660c-66bf-11e2-8651-c1548e3ec3cf.PNG)

**Comment by JakobTischler** [comment]
Please try to not repost existing issues. See issue #45
