### ISSUE TITLE
Alignment problem when combine resumes harvesting

### ISSUE THREAD

**Issue by Psytronex** [netjungle/courseplay#48]
In "Combi unloads itself" mode, when the combine returns to the field and rehires a worker, about 50% of the time the combine doesn't line up properly from where it left off, and there is left a whole line of crops which the combine misses for the rest of the row.

Possibly, when autoplay takes the combine back to approximately the right point where it left off, and then the hired worker straightens up the combine, it is no longer in the same place as it left off, causing large sections of crops not to be harvested.

(I do have a screen print, but the forum software doesn't want to attach it for me)

**Comment by JakobTischler** [comment]
Yeah I know what you're talking about, I've also seen it - although only with harvesters (potatooes and beets). Does this also happen with regular combines?

**Comment by Psytronex** [comment]
Yes.  I'm using the Fahr M66.

**Comment by JakobTischler** [comment]
Copied this into the bugtracker. Thanks.
