### ISSUE TITLE
Idear for a new course making or edit

### ISSUE THREAD

**Issue by Goten87** [netjungle/courseplay#49]
well i think its more for nice editing
can u make a edit system so we can edit like we are placing the or moving the eggs and other points with the placeable object screen and then we can add eggs or remove or move the points

so we have a nice edit screen when u want to chance some courses

a little like the Courseplay Editor program only ingame

sorry for my bad English not my main language

**Comment by JakobTischler** [comment]
Maybe in 2 years when anyone has access to the ingame placement screen. Or when we've fixed most of the bugs currently existing. 
Sorry, but what you suggest would be so immensly difficult to create ingame that I can only say it would not even be on a to do list right now.
