### ISSUE TITLE
Out of fuel, but still able to drive

### ISSUE THREAD

**Issue by DeckerMMIV** [netjungle/courseplay#50]
When a vehicle has no fuel left and its engine turned off, Courseplay is still able to make it drive around.

Maybe only allow Courseplay to work, when engine/motor is turned on?

**Comment by JakobTischler** [comment]
The engine check could be rather difficult, given that standard models don't even distinguish between both states. If you're inside, it's turned on, when not, it's turned off, unless it's in helper mode. Which is kinda what we're using here.

I'll have to have a look at the manual ignition scripts to see if some discrimination could be incorporated.

Concerning the no fuel, no drive policy - I think that should be achieved easily. Again, I'll look into it. Though I have to say I've never experienced a situation like that. Long before it's empty I'm getting fuel warnings, and with some luck I have it on a route where it refills automatically.

**Comment by JakobTischler** [comment]
As a followup: What's the situation where you have no fuel? CP has a conditional go/no-go based on fuel percentage, specifically:

``` lua
if currentFuelPercentage < 15 then
    allowedToDrive = false
    self.global_info_text = self.locales.CPNoFuelStop
end
```

Meaning, if the tractor has less than 15% of fuel left, it should stop and display a message ("XYZ must be refueled").

**Comment by DeckerMMIV** [comment]
I let a standard tractor drive continuously until it runs out of fuel, not having it touch any fuel-triggers. When reaching zero fuel, it still drives around.

Looking at the code in drive.lua, I think the first conditional expression is the cause:

``` LUA
if currentFuelPercentage < 20 and not self.isFuelFilling then
  ...
elseif currentFuelPercentage < 15 then
  ...
end
```

since isFuelFilling is always false, and the fuel percentage is below 20, it will never get to the 'elseif below 15' statement.

Also it looks to me, that the variable `currentFuelPercentage` may be able to be NIL, if the vehicle has fuelCapacity <= 0, possibly making the next if statements cause errors when comparing a NIL value to a number.

**Comment by JakobTischler** [comment]
Decker, please replacing the existing segment with the following and try again.

``` lua
        local currentFuelPercentage = (self.fuelFillLevel / self.fuelCapacity + 0.0001) * 100;
        if currentFuelPercentage < 15 then
            allowedToDrive = false
            self.global_info_text = self.locales.CPNoFuelStop
        elseif currentFuelPercentage < 20 and not self.isFuelFilling then
            self.global_info_text = self.locales.CPFuelWarning
            if self.fuelFillTriggers[1] then
                allowedToDrive = false
                self:setIsFuelFilling(true, self.fuelFillTriggers[1].isEnabled, false)
            end
        elseif self.isFuelFilling then
            allowedToDrive = false
            self.global_info_text = self.locales.CPRefueling
        end;
```

**Comment by DeckerMMIV** [comment]
Putting your patch into the `if self.fuelCapacity > 0 then ... end;`, and removing the other statements, fixes the out of fuel problem.

Thank you. Closing this issue.

**Comment by JakobTischler** [comment]
@DeckerMMIV, is there any way to contact you directly? Please drop me an email at my account's email address.
