### ISSUE TITLE
speed control is uneven

### ISSUE THREAD

**Issue by abehnke** [netjungle/courseplay#51]
I am using the Deutz M620 tractor, and I noticed that when CP is driving the speed varies up and down as if hunting for a set point.  If I set 15 mph, then the speed goes up and down 12 to 15mph. The ZIP file is from github on Jan. 29, 2013.

I experiment with a different schedule of RPM in drive.lua courseplay:setSpeed.  No great control theory went into my version.  I just thought maybe powers of 2 might be better. 

```
        if refSpeed*3600 - self.lastSpeedReal*3600 > 2 then
            maxRpm = maxRpm + 20
        elseif refSpeed*3600 - self.lastSpeedReal*3600 > 1 then
            maxRpm = maxRpm + 10
        elseif refSpeed*3600 - self.lastSpeedReal*3600 > 0.5 then
            maxRpm = maxRpm + 5
        end
        if self.lastSpeedReal*3600 - refSpeed*3600 > 2 then
            maxRpm = maxRpm - 20
        elseif self.lastSpeedReal*3600 - refSpeed*3600 > 1  then
            maxRpm = maxRpm - 10
        elseif self.lastSpeedReal*3600 - refSpeed*3600 > 0.5 then
            maxRpm = maxRpm - 5
        end
```

**Comment by Kobe8** [comment]
I had experienced the same issue. When the speed is set to 25 km/h is goes up to 28 and down to 22.

Another things is when i ran a combine course, the tipper is full and the tractor is driving back. it slows down to 8 to 11 km/h not to the speed that was set in CP.

**Comment by JakobTischler** [comment]
The first issue has been / is being fixed as we speak. The ESLimiter version of is already working (locally, not online yet), the standard RPM version is next. Expect a push with the fix either later tonight or tomorrow.

The slow speed when driving back has also been fixed, will be pushed in the next couple of days.

@Kobe8: for future reference, if you have seperate bug, please post it as a new issue, not within an existing one, even though it might be under the same topical umbrella (in this case 'speed').

**Comment by JakobTischler** [comment]
Actually I'll re-open this until the new speed stuff is online and you can test it - and better approve of it ;)

**Comment by Kobe8** [comment]
speed control is much smoother right now! good job!

**Comment by JakobTischler** [comment]
Could more people confirm this please? The more approve of the current settings and handling, the faster we can move on to other bugs.

**Comment by abehnke** [comment]
Yes indeed - speed control is fine now.  Thank you.

Here are some tests:

SAME 75 hauling wool with the blue wagon - GOOD

Next are all using the Deutz M620 at various speeds:
Nothing attached  - GOOD
Mowing at 25 kph with Kuhn mowers in front and back - GOOD
Hauling Garant 19500 tank - GOOD
Hauling Krampe 900 loaded and unloaded - GOOD
Hauling Krampe 900 to unload Grimme 415 in Combi mode - GOOD

**Comment by JakobTischler** [comment]
Thanks for the tests. I'll close this one then.
