### ISSUE TITLE
combine mode uses turn maneuver speed when full

### ISSUE THREAD

**Issue by Kobe8** [netjungle/courseplay#52]
the combine is driving with 10 km/h back to the starting point of the route instead of field speed!

**Comment by JakobTischler** [comment]
Is fixed, still testing locally, when tests are successful I'll push it online.

**Comment by JakobTischler** [comment]
Those are internal development entries. As long as there are no warnings and/or errors, those are always there on purpose.

If the tractor is circling, you have set the turn radius too low. Increase it and try again.
