### ISSUE TITLE
Tipper not tipping at Freight Yard

### ISSUE THREAD

**Issue by abehnke** [netjungle/courseplay#56]
When entering the tipping zone at the Freight Yard,  I see the tip symbol appear but CP does not stop and do the tip operation.  (Using ZIP file download Feb. 1, 2013).  It appears the distance never gets below 20 so the self.currentTipTrigger gets reset back to nil.  I think this is a different problem than the one just reported by Satissis "Some tippers dont tip at tip triggers (A fix for it)"

I inserted some "print"s in mode1.lua:

---

```
if self.currentTipTrigger ~= nil then
    local trigger_id = self.currentTipTrigger.triggerId

    if self.currentTipTrigger.specialTriggerId ~= nil then
        trigger_id = self.currentTipTrigger.specialTriggerId
    end

    local trigger_x, trigger_y, trigger_z = getWorldTranslation(trigger_id)
    local ctx, cty, ctz = getWorldTranslation(self.rootNode);
    local distance_to_trigger = courseplay:distance(ctx, ctz, trigger_x, trigger_z)
    print("distance: "..distance_to_trigger)
    if self.currentTipTrigger.bunkerSilo ~= nil then
        if distance_to_trigger > 60 then 
            print("set nil 1")
            self.currentTipTrigger = nil
        end
    elseif  
        distance_to_trigger > 20 then
            print("set nil 2")
            self.currentTipTrigger = nil
    end --!!!

end
if self.currentTipTrigger == nil then
    print("trigger nil")
else
    print("trigger: "..self.currentTipTrigger)
end     
-- tipper is not empty and tractor reaches TipTrigger
if tipper_fill_level > 0 and self.currentTipTrigger ~= nil and self.recordnumber > 3 then
    self.max_speed_level = 1
    print("aaa")
    allowedToDrive = courseplay:unload_tippers(self)
```

---

part of log.txt - (there are also some prints in triggers.lua - ignore those)

trigger nil
trigger nil
trigger nil
trigger nil
trigger: TipTrigger  fruit: 3  current:3
accepted in trigger
distance: 23.253820915216
set nil 2
trigger nil
trigger: TipTrigger  fruit: 3  current:3
accepted in trigger
distance: 23.181864814722
set nil 2
trigger nil
trigger: TipTrigger  fruit: 3  current:3
accepted in trigger
distance: 23.109953434806
set nil 2
trigger nil
trigger: TipTrigger  fruit: 3  current:3
accepted in trigger
distance: 23.038124638636
set nil 2
trigger nil
trigger nil
trigger nil
trigger nil

**Comment by ThomasGaertner** [comment]
yes there's a problem because the trigger is too slim , so it won't be reconised correctly. at this moment I try something with Satissis solution, maybe it fixes also  this issue.

**Comment by ThomasGaertner** [comment]
do you mean the freight yard or the railway station?? @ freight yard I had no probs so far

**Comment by abehnke** [comment]
In my version of FS2013 (I am in USA), there is no tip point called railway station.  The one by field 10 is called "Freight yard",  and it does have rail cars near the tip point.  It is one of the few (or only) fruit tip points that does not use the drive-over grate.
