### ISSUE TITLE
Game crash if endpoint is reached

### ISSUE THREAD

**Issue by TobiTo83** [netjungle/courseplay#59]
Already posted here: http://forum.farming-simulator.com/viewtopic.php?f=769&t=51291&p=418176&sid=f6d0339199167aa553a0a3ea9aacf6c1#p418176

Today i get the same issue with another course which worked correctly in past. i used the same vehicles but i get a reproducable error and the game is crashed!

F:/Users/T/Documents/My Games/FarmingSimulator2013/mods/Krampe_Bandit_980_gruen/TowBall.i3d (0.19mb in 10.98 ms)
Error: LUA running function 'update'
F:/Users/T/Documents/My Games/FarmingSimulator2013/mods/ZZZ_courseplay/combines.lua(241) : attempt to index field 'trafficCollisionIgnoreList' (a nil value)
Error: LUA running function 'update'
F:/Users/T/Documents/My Games/FarmingSimulator2013/mods/ZZZ_courseplay/combines.lua(251) : attempt to index field 'trafficCollisionIgnoreList' (a nil value)
Error: LUA running function 'update'
F:/Users/T/Documents/My Games/FarmingSimulator2013/mods/ZZZ_courseplay/combines.lua(251) : attempt to index field 'trafficCollisionIgnoreList' (a nil value)
Error: LUA running function 'update'
F:/Users/T/Documents/My Games/FarmingSimulator2013/mods/ZZZ_courseplay/combines.lua(251) : attempt to index field 'trafficCollisionIgnoreList' (a nil value)
Error: LUA running function 'update'
F:/Users/T/Documents/My Games/FarmingSimulator2013/mods/ZZZ_courseplay/combines.lua(251) : attempt to index field 'trafficCollisionIgnoreList' (a nil value)

**Comment by JakobTischler** [comment]
Please use the current developer version, not the public release version and try to reproduce _this_ error. The one you've posted at the official forum is not related to this one. Please post that one seperately as an issue.

**Comment by TobiTo83** [comment]
okay i've downloaded dev version. the issue is still present.

logs:
F:/Users/T/Documents/My Games/FarmingSimulator2013/mods/Krampe_Bandit_980_gruen/TowBall.i3d (0.19mb in 10.94 ms)
combines.lua(242): SchlÃ¼ter Super Trac 2500 VL @ ClaasJaguar980: combine.forced_side=nil
combines.lua(253): SchlÃ¼ter Super Trac 2500 VL @ ClaasJaguar980: combine.forced_side=nil, going by fruit
Error: LUA running function 'update'
F:/Users/T/Documents/My Games/FarmingSimulator2013/mods/ZZZ_courseplay/combines.lua(308) : attempt to index field 'trafficCollisionIgnoreList' (a nil value)
Error: LUA running function 'update'
F:/Users/T/Documents/My Games/FarmingSimulator2013/mods/ZZZ_courseplay/combines.lua(318) : attempt to index field 'trafficCollisionIgnoreList' (a nil value)

the second error is written to the log again and again until i destroy ls application

At the moment i use the Patch 1.4 Alpha

**Comment by JakobTischler** [comment]
Try activating line 352 in base.lua by changing

``` lua
    --  self.trafficCollisionIgnoreList = {};
```

to

``` lua
    self.trafficCollisionIgnoreList = {};
```

_Note:_ this is only a temporary solution.

**Comment by JakobTischler** [comment]
Nevermind the comment  above. Do you happen to try to unload an attachable combine (e.g. Grimme Rootster)? Those aren't supported yet.

**Comment by JakobTischler** [comment]
No answer - closed.
