### ISSUE TITLE
a french traduction ?

### ISSUE THREAD

**Issue by gui7545** [netjungle/courseplay#60]
hello everybody
I am a french guy and I would like to do a French traduction of this project.
I seek a little bit what I can do to help this project and I propose to translate modDesc.xml
If you want, I can add this tags for each lines: Example for the first one
![Capture](https://f.cloud.github.com/assets/2854643/122035/9010ba64-6e25-11e2-88c6-063f3d0e26b7.PNG)
And, because I am French. I think that I will not do mistake in translation.
To reassure you, I have my First Certificate in English – FCE
Thank you
Guy7545

**Comment by JakobTischler** [comment]
Hi Guy,

many thanks for the offer. Could you please contact me via my account email? We could then discuss further proceedings.

**Comment by gui7545** [comment]
Done
