### ISSUE TITLE
Bale autostacker does not dump and return

### ISSUE THREAD

**Issue by abehnke** [netjungle/courseplay#64]
The Arcusin Autostack running in Fieldwork mode does not appear to do the following Fieldwork actions:  "It will drive the course until full, record it's position, drive to the endpoint(waitpoint) of the field then continue it's course over the dump point, dump and return to the recorded position to work the rest of the field."  I placed some print's in mode6.lua, and it appears that the Arcusin Autostack trips 
"if SpecializationUtil.hasSpecialization(BaleLoader, workTool.specializations)"
Therefore, it does not setup  "abortWork" as a forager would.  Using ZIP file download Feb. 4, 2013.

**Comment by JakobTischler** [comment]
Does it even activate and pick up the bales? If not, you might be right about it not recognizing the specialization.

Try the following please: 
with the very latest (08 Feb, 5:45 pm EST) version, in `tippers.lua` and `mode6.lua` change every

``` lua
if SpecializationUtil.hasSpecialization(BaleLoader, workTool.specializations) ...
```

to

``` lua
if SpecializationUtil.hasSpecialization(baleLoader, workTool.specializations) or SpecializationUtil.hasSpecialization(BaleLoader, workTool.specializations) ...
```

It _could_ be that Giants has changed the specialization name so that the LS11 one isn't recognized anymore.

**Comment by abehnke** [comment]
Yes it picks up bales.  This Arcusin Autostack behaves like a forage wagon.  On manual, the B key extends a collector then all I do is drive past bales and it fetches and stacks up to 18 of them.  Every other bale there is an extra animation as the tool pushes 2 bales onto its stack.  When CP is in control in Fieldwork mode, when this animation occurs, it halts the tractor for a few seconds.  This is harmless but useless since the Autostack can drive and do is internal stacking stuff at the same time.   I applied your suggested code changes to a ZIP file fetched on Feb. 8 at 10:17pm EST.  I switch workTool to object in tippers.lua since workTool produced an error.  The change had no effect.  I put a display in front of the if

```
        if SpecializationUtil.hasSpecialization(baleLoader, workTool.specializations) then
            print("baleLoader true")
        elseif SpecializationUtil.hasSpecialization(BaleLoader, workTool.specializations) then
            print("BaleLoader true")
        else
            print("false")
        end 
```

This reported BaleLoader true. Actually I think all would work better if this if was not true at all - so I removed both and just left: 

```
        if  courseplay:isUBT(workTool) then
```

Result of this experiment was success.  Now, the Autostack is treated as if it were a forage wagon.  When full it remembers its spot and does the unload loop. I assume this not the way to fix this since I guess it would break real balers, baleloaders.

**Comment by JakobTischler** [comment]
Yeah, must be `object` in `tippers.lua` of course, my bad.

Oh, I thought you were talking about one of the standard bale loaders (or maybe there is only one? - I can't remember). If the Arcusin is a mod (do you have a link, please, so I can look at it and maybe include a conditional for it?) that doesn't use the standard baleLoader methods then no, it wouldn't work out of the box.

**Comment by abehnke** [comment]
The Arcusin Autostack comes with the game.  It is at the game store under "Baling Technology".

**Comment by JakobTischler** [comment]
@abehnke, could you please test if all works with the latest commit (https://github.com/netjungle/courseplay/commit/3fc437f89f139c1c4613318f1d214efcd57c2f8b) ?

We can't deal with a bale loader as if it's a forage wagon for a multitude of reasons, mostly because we have to handle far more stuff like work/transport position, grabber position etc.

**Comment by abehnke** [comment]
Works great now. When the Arcusin Autostack has 18 bales, it remembers its abort waypoint, runs the unload loop and returns to field to continue work.  For fun, I placed a 3rd wait point  where I wanted it do the unload. I thought it might pause but it went ahead and automatically unloaded the stack under CP control. Of course, this is only good for once around the loop since the tractor would crash into the bale stack on a second go around. That's ok with me - I am not expecting Courseplay to handle that situation.  The very minor issue of the tractor waiting for the Arcusin Autostack animiation to run every 2 bales is still present - not really a bug - just an interesting side effect.

Thanks again for all the fine Courseplay improvements.

**Comment by JakobTischler** [comment]
Great to hear, thank you. I've been wondering about what went wrong for a while.

If you're interested in what went wrong: the problem wasn't really that the tool was handled as a bale loader. It was rather when dealing with it as a bale loader, we didn't set an abort work point, we didn't tell him to head to the last waiting point and then drive the unloading course and so on.

Concerning the stopping while the animation is running: it might be true for the Arcusin that it manages to play the full animation on its way to the next bale. But it might not be true for a different bale loader. Or it might not be true if the bales are closer to each other than by default. So ... safety first :)
