### ISSUE TITLE
in traffic when turning with a foldable harvester header

### ISSUE THREAD

**Issue by isycz** [netjungle/courseplay#68]
generate a course for a field. Working width of 10.5m

forage harvester with foldable corn header stops at the end of the field before turn and reports it is in traffic

tried with several folding headers including the one provided with the game. all have similar issue.

also tried with non-folding 6m and 12m corn header and harvester turns without issue

**Comment by JakobTischler** [comment]
The problem is the combine sees the cutter as a traffic object. Just like, for example, the GTA 380 sees its front loader or the attached implement as a traffic object.

We're working on a fix.
