### ISSUE TITLE
Amazone condor 15001 Breakes the game

### ISSUE THREAD

**Issue by Goten87** [netjungle/courseplay#69]
When i have a Amazone condor and a Case IH Quadtrac or Steiger connected
and i release then then the game will crash and i cant do anything anymore with my keyboard its like the game is freezing but when i right click i get the Courseplay screen
i cant press esc and i'm forced to kill the game without saving
i tested it on multilayer with only 1 mod on and when i got to courseplay it happend so i debugged it to this mod

sorry for my bad English not my main lang

**Comment by ThomasGaertner** [comment]
please send us the log

**Comment by Satissis** [comment]
@Goten87 Did the log file show any errors ??
Without the log file we won't be able to guess what the error is.

**Comment by Goten87** [comment]
where can i find the log file

**Comment by JakobTischler** [comment]
Sorry to say this, but if you don't know how to find and interpret the log file, maybe the _developer version_ is not really the right thing for you.

**Comment by Goten87** [comment]
ok i downloaded today a new version of courseplay and now the bug is gone ^^
