### ISSUE TITLE
Course over tip point must be precise

### ISSUE THREAD

**Issue by abehnke** [netjungle/courseplay#70]
I had some tippers not tipping at the farm's silo.  I believe I have used this course in  past weeks with no problem. The course (used in Combi mode) does not go exactly over the middle of the grate area.  (I laid it out poorly) It goes along one edge but it is good enough to turn on FS13 tip symbol. I can drive and tip manually when over to the side like this.  I made another course to confirm the problem - a simple loop around the farm silos.  I run this in DriveHelper mode and the problem is present. Using ZIP downloaded Feb. 8, 2013.  This is small issue - I hope I am not being too picky.

Thanks to the Courseplay team for all the fine updates over the past weeks.

![fsScreen_2013_02_08_10_55_49x](https://f.cloud.github.com/assets/3346683/139950/64c1be8c-720b-11e2-8ff6-d943522291a6.jpg)

**Comment by ThomasGaertner** [comment]
this happens , when the trailer has no valid tip refernce point in the tip trigger. the trailer you used has only 2 points: one in the back and one on the lefhand side. this also happens @ the freight yard, if you try to tip with a trailer which has no tip reference point on the "train-side" . the manual function is slightly more tolerant concerning validtion of tip raference points

**Comment by abehnke** [comment]
Thanks for explaining about tip reference points. I only now realize the some of the wagons only dump from one side - I was not paying close attention to what they actually do when tipping.

I was wondering if the tolerance could be changed to be more like when in manual drive.  I was having a hard time making tips that work in CP at the beet silo and the grass/straw tip point (west side brown shed). So, I started experimenting with follwing "if" in tippers.lua function courseplay:unload_tippers.  The conditional had a predicate of == 0 so I changed it to < 1.0.  The result - with very limited testing (1) - seem that now CP tips at about the same time the FS13 tip symbol appears. I suppose the problem in doing this change would be that the tip action can occur a meter outside the area that the map designer intended?

```
        if tipper.tipState == Trailer.TIPSTATE_CLOSED then
            print("aaa: "..self.currentTipTrigger:getTipDistanceFromTrailer(tipper, tipper.currentTipReferencePointIndex)) 
            if self.currentTipTrigger:getTipDistanceFromTrailer(tipper, tipper.currentTipReferencePointIndex)  < 1.0 or self.currentTipTrigger.bunkerSilo ~= nil then   --courtesy of Satis
```

Using ZIP file download on Feb. 9, 2013 and FS13 1.4.

**Comment by Satissis** [comment]
@abehnke If you change the  == 0 to < 1.0 then you will run into the old error with some tippers where the tipper freezes

**Comment by abehnke** [comment]
Ok Satissis, I will change it back to == 0.  I will just have to practive doing this tip manueuver better.  I also have attached another image documenting about when FS13 puts up the tip icon  It seems to be around 1 meter from the tip area. This test is with == 0 on the "if" and a "print" directly before it. CP did not tip.  So as soon as I saw the icon, I pressed Prt Screen.  This is using the same ZIP as my prior post and the tipper is a Krampe 500 with beets at the farm silo Combi mode.

![fsScreen_2013_02_09_22_41_09y](https://f.cloud.github.com/assets/3346683/142899/8b9fe97a-7337-11e2-90f5-63050f52db71.jpg)

**Comment by abehnke** [comment]
I have discovered another aspect to this drive-by tipping maneuver that is needed for tip triggers such as the grass/straw shed on the west side of the farm.  If I approach the tip point almost parallel to the opening (say from due south) then the raycastall function cannot see the tip trigger and thus does not setup currentTipTrigger.  Instead, it works better if I aim directly for the tip area at some angle and wait until within 10 meters of the opening.  At that point, I can swing more parallel to the opening then swing out to get part of the wagon's rear into the opening. From my point of view, these aspects of the drive-by maneuver for the tippers and triggers aren't really something that needs fixing - maybe just some hints in the readme.txt would be good.  I was testing using a ZIP (2013-02-13 15:19) and Fieldwork mode with straw, Krone 550.

**Comment by JakobTischler** [comment]
Thanks for the heads up. I'll see if I can add this to the manual.
