### ISSUE TITLE
recurring errors

### ISSUE THREAD

**Issue by wevee** [netjungle/courseplay#72]
since getting the latest version today (Feb 8) I am getting constant log writing of the following two errors:

Error: LUA running function 'update'
C:/Users/wevee/Documents/My Games/FarmingSimulator2013/mods/ZZZ_courseplay/drive.lua(679) : attempt to perform arithmetic on field 'lastSpeed' (a nil value)

Error: LUA running function 'update'
D:/Code/Giants/lsim2013/build/finalbin/dataS/scripts/Utils.lua(104) : attempt to perform arithmetic on local 'x' (a nil value)

Leaves game frozen while writing, forced exit required.

**Comment by wevee** [comment]
Additional info.  Error occurs while running a combined combi course, after clicking 'send driver home' from harvester driver management screen

**Comment by ThomasGaertner** [comment]
could you please tell us, which tractor  U used ? did U have a weight or something on the front attacher ?
if yes , please try without something on Ur front attacher and report the result
THANKS

**Comment by wevee** [comment]
tractor: huerlimannXL130
front attachment:  barrel weight
rear attachment:  kroeger agroliner hkd302 (21,000L tipper)

first attempt: with weight on front, I am able to reproduce errors on first trip.
second attempt: without weight on front, I am not able to reproduce error in three trips
third attempt:  with weight on front, same as first attempt.

Let me know if you would like any other information please.

related mods:  map is "two rivers",  "eslimiter" 

Edit:  I retested using a deutzTTV430 and got the same results both with and without the barrel weight.

After several more attempts, I was able to get the same errors without a front weight attached on a deutzTTV430
