### ISSUE TITLE
Fertilize mode "unloading bales"

### ISSUE THREAD

**Issue by Voidheartd** [netjungle/courseplay#74]
I attempted to setup a course to fertilize field 14 and 15/16. After telling it to continue after it completes 14 and reaches the end wait point, it goes to the start wait point for 15/16 which is done second, it stops and I get the message "Buehrer 6135 A unloading bales." Is this mode not designed for multiple spray starts and stops or is this just a bug?

I'm using a Buehrer 6135 A + Weight + Amazone ZG-B 8200, and the latest courseplay files.

I currently have changed the middle wait points to regular wa points to avoid this.

**Comment by JakobTischler** [comment]
Multiple starts/stops (via waitpoints) are currently not supported at all. When using fertilizer/seeding mode, you have to make sure that you only have exactly two wait points in the whole course. Meaning: when combining the field course with, say, a course where you refill you tool, you will need to only have 2 wait points total: the start of the field area and the end of the field area.
