### ISSUE TITLE
Combines ignoring nearby vehicles at end of row

### ISSUE THREAD

**Issue by Voidheartd** [netjungle/courseplay#75]
With the latest files combines are now ignoring an unloading tractor (whether on a course or manual) when they reach the end of a row and finish unloading, which leads to the combine driving up the side of the tractor.

**Comment by ThomasGaertner** [comment]
did you use the helper mode (AI) for the combine or which mode did you use??

**Comment by Voidheartd** [comment]
Yes it was helper mode. It appears this affects anything in helper mode.
