### ISSUE TITLE
Vehicle in traffic causes error

### ISSUE THREAD

**Issue by wevee** [netjungle/courseplay#76]
I saw the last error I had reported was closed, however it was not totally solved.  The error the game throws now no longer references the courseplay mod, but still flags the same update function in utils.lua.  

Error: LUA running function 'update'
D:/Code/Giants/lsim2013/build/finalbin/dataS/scripts/Utils.lua(104) : attempt to perform arithmetic on local 'x' (a nil value)

I have tested farther and have found what I believe to be the cause.  I can recreate this easily now.  On the map "two rivers"  there are some train tracks that can put the vehicle into traffic for up to 25 seconds.  After the crossing arms lift, the vehicle (I have tested several, all with the same results) will attempt to move when the error is thrown, causing game freeze and forced abort is required.

<img src="http://img7.imageshack.us/img7/8443/fsscreen20130212190847.png" />

I have attempted to recreate it on other maps using vehicles but not much luck with that so far.  I admit it could be a map specific error, however I have seen 4 maps now using the same train/crossing.  When I open up the map.i3d I see there are 2 collision triggers, 1 on either side of the crossing, of the type 'kinematic'.  I don't know if that helps at all.

**Comment by ThomasGaertner** [comment]
which version did U use in this moment ? it is supposed to be fixed with the fix from 10.feb 8:50 .
can you confirm the failiure after this fix?

**Comment by wevee** [comment]
Yes, I can confirm that I am using the update from 3 days ago, "a tribute to BigM in MODE6"

**Comment by ThomasGaertner** [comment]
hmm , thats not good . I couldn't get it. it works fine  while testing. could anyone else confirm this problem ?

**Comment by wevee** [comment]
Here is the debug listing up until the error

....
data/vehicles/cars/car3.i3d (0.39mb in 43.17 ms)
data/vehicles/cars/car7.i3d (0.47mb in 70.91 ms)
courseplay:update_tools() (Schlueter Super Trac 2500 VL)
Kroeger Agroliner HKD 302 is in front - adding to cpTrafficCollisionIgnoreList
Schlueter Super Trac 2500 VL cpTrafficCollisionIgnoreList
76767 = Schlueter Super Trac 2500 VL
77237 = Kroeger Agroliner HKD 302
found trigger
checking CollisionIgnoreList
107 vs nil
108 vs nil
found trigger
checking CollisionIgnoreList
107 vs nil
108 vs nil
Error: LUA running function 'update'
D:/Code/Giants/lsim2013/build/finalbin/dataS/scripts/Utils.lua(104) : attempt to perform arithmetic on local 'x' (a nil value)
Error: LUA running function 'update'
D:/Code/Giants/lsim2013/build/finalbin/dataS/scripts/Utils.lua(104) : attempt to perform arithmetic on local 'x' (a nil value)
Error: LUA running function 'update' ......

That is with all mods stripped out except for eslimiter, two rivers and courseplay of course.

Edit:  I just retested with only two rivers and courseplay and same results, had to be sure there wasn't some conflict with eslimited.  I should have been more specific, this is on two_rivers_english.  I don't think there would be a difference in two_rivers_de but I am downloading it now to double check.

**Comment by JakobTischler** [comment]
No need to download the German version, it's virtually identical. You could try the following:
with the very latest version, change the following in `drive.lua`, line 506:

Old:

``` lua
if vehicle_in_front.rootNode == nil or vehicle_in_front.lastSpeedReal == nil or courseplay:distance_to_object(self, vehicle_in_front) > 40 or vehicleBehind then  --!!!
```

New:

``` lua
if vehicle_in_front.rootNode == nil or vehicle_in_front.lastSpeedReal == nil or (vehicle_in_front.rootNode ~= nil and courseplay:distance_to_object(self, vehicle_in_front) > 40) or vehicleBehind then  --!!!
```

**Comment by wevee** [comment]
That appears to have cleared the error, thank you!  I got the German version anyways, I liked some of the textures better :P 

courseplay:update_tools() (Schlueter Super Trac 2500 VL)
Kroeger Agroliner HKD 302- adding to cpTrafficCollisionIgnoreList
Schlueter Super Trac 2500 VL cpTrafficCollisionIgnoreList
76763 = Schlueter Super Trac 2500 VL
77230 = Kroeger Agroliner HKD 302
found trigger
checking CollisionIgnoreList
Schlueter Super Trac 2500 VL vs nil
Kroeger Agroliner HKD 302 vs nil
found trigger
checking CollisionIgnoreList
Schlueter Super Trac 2500 VL vs nil
Kroeger Agroliner HKD 302 vs nil
