### ISSUE TITLE
Forage wagons mode error

### ISSUE THREAD

**Issue by silvaport** [netjungle/courseplay#77]
In forage wagons mode doesn't stop on the unload triggers

**Comment by JakobTischler** [comment]
Which vehicles, which trailers, what does the log say?

**Comment by silvaport** [comment]
Still not unloading! I tested with a lot of vehicles and trailers still crossing the discharge points without unload

**Comment by JakobTischler** [comment]
What trailers? What fruit type? Where are you trying to unload? Which mode are you using?

**Comment by silvaport** [comment]
I tested with several trailers collecting grass and tried to unload on BGA and grass deposit but does not stop in any of them, the mode is fieldwork for balers, forage wagons, baleloaders.

I don't know if I'm doing something wrong

1 Start course recording
(cross the unloading point)
2 Set waitpoint
(course the field)
3 Set waitpoint
4 Stop course recording (close to start)

It works fine in LS2011

**Comment by abehnke** [comment]
Could it be this problem https://github.com/netjungle/courseplay/issues/39 ?

**Comment by ThomasGaertner** [comment]
yea . getFruitTypes guves back the Fruit, type :-)
even it's straw from wheat, getFruittype gives back wheat

**Comment by silvaport** [comment]
Good job Thomas many thanks...
