### ISSUE TITLE
Amazone UX 5200 folding/unfolding is crossed

### ISSUE THREAD

**Issue by Rodberaht** [netjungle/courseplay#78]
When in Mode 4 (fertilizing/seeding)(?) Amazone UX 5200 fertilizer is unfolding at the start of the course and folding at the first breakpoint. The fertilizing is started correctly at the first breakpoint but with a folded fertilizer that makes no sense. The problem exists since the commit "mode4: seeding / mode6: more supported tools" Had unfortunately no chance to test it with other fertilizers.

**Comment by JakobTischler** [comment]
Working on a fix right now. Standard machinery worked fine in my last tests, certain mods didn't. Though we will have to draw the line somewhere as we can't support every single mod.
