### ISSUE TITLE
Problem with combi mode

### ISSUE THREAD

**Issue by Raints** [netjungle/courseplay#82]
Also small problem with refueling, tractor stops at fuel trigger, start fueling and then continue along the path. Will get full tank, but wont stop for refueling.

I do not know what causes it but the tractor is too far from big x. Using version downloaded 16.02.2013

![fsScreen_2013_02_17_14_33_06](https://f.cloud.github.com/assets/3618060/165022/836f8fb6-790f-11e2-9d77-de7c2a398487.png)

![fsScreen_2013_02_17_16_28_02](https://f.cloud.github.com/assets/3618060/165025/ab90e436-790f-11e2-873f-84dc063f32d4.png)

**Comment by JakobTischler** [comment]
Is this reproducable? None of us have experienced this bug before. Also, it might be smart, when testing, not to use 3 or more drivers at the time, but only one.

**Comment by JakobTischler** [comment]
No answer - closed.
