### ISSUE TITLE
Waypoint accuracy

### ISSUE THREAD

**Issue by loza84** [netjungle/courseplay#83]
Im not sure if this is the correct kind of issue for here but it seems like the best place to ask (that isnt in german) and im sorry if i have done wrong, but the problem im having is recording courses on smaller maps, the waypoints are too far apart and the tractors always end up cutting the corners and getting stuck, making it hard if not impossible to use courseplay on certain maps. I was just wondering if it was possible to change how often it adds a waypoint so they go Around the corner rather than through it.

Im sure this was never a problem in the 2011 version so it must be a recent change.

 Thanks, loza

**Comment by JakobTischler** [comment]
This has already been added to the bugtracker (https://www.pivotaltracker.com/story/show/43046753). Problem with this is, some people have no problem with how accurately the waypoints are used, some (like you and even me) do. So for now I don't have a definitive fix that applies to _everyone_. 

What's not gonna happen is us setting the waypoints more often, but rather setting the accuracy of how they're used.

What I personally did (on my setup), and you could try and test this with yours, is lowering the _distance to change_ (`distToChange`). With the current version, you'd need to edit two values in `drive.lua`:

Lines 610 and 613, change from `5` to

``` lua`
distToChange = 2.845
```

As a note, again: this works for me. It might not be for you. It also depends how ... let's say "accurately" the courses are recorded, how narrow the corners are etc.

**Comment by TheCadde** [comment]
You can also create waypoints manually by pausing and resuming your recording. Though i am not sure if the above condition still applies. (min distance being 5 meters)

Might be worth a try? Then you force higher accuracy when making turns by pausing and resuming as frequently as you'd like. But beware, if your vehicle misses a waypoint it can get horribly stuck either way. It can miss a waypoint if they are too close together.

**Comment by JakobTischler** [comment]
Fixed by https://github.com/netjungle/courseplay/commit/c0d92f4efe0233845da189642d5a8dd48679ebff
