### ISSUE TITLE
tipper not dumping at freight depot

### ISSUE THREAD

**Issue by Brzzl** [netjungle/courseplay#85]
downloaded the latest version today and wanted to carry grain maize from my farm on the standard map to the freight depot... unfortunately the tippers were not dumping there... the tractors were slowing down and driving over the trigger but nothing happens and they were continue there track without unloading. with an older version of courseplay I haven't this issue...

edit:
tested it just by replacing the mode1.lua from a version of courseplay I downloaded on februar 3rd and the problem still exists... looks like the problem is obviously not only inside the mode1.lua...more an interaction with other files... replaced the whole files of courseplay with the older version and it woks fine...

**Comment by ThomasGaertner** [comment]
the freight yard requires trailers, which have tip-points on the related side. Did U use a trailer able to tip right/left??

**Comment by Brzzl** [comment]
certainly not! :D used the Gilibert 1800 Pro... so for my understanding: it is a feature not a bug that I have to use a side-dumping-able tipper now?

**Comment by ThomasGaertner** [comment]
i would say, it's more realistic ;-) , there is a technical reason as well : the tip trigger is very slim, so the back-tip tippers can not reach it.

**Comment by Brzzl** [comment]
I see... thank you :)

**Comment by Voidheartd** [comment]
Couldn't you setup the route such that the tipper gets backed up to the dump spot?

**Comment by Brzzl** [comment]
sure I could... but that would mean I have to make a new route and we all know: time is money ;) it was easier to buy a new tipper :D
