### ISSUE TITLE
Drive now keybind only works when on control menu

### ISSUE THREAD

**Issue by Voidheartd** [netjungle/courseplay#86]
I've noticed that the keybind for drive now only works if you are on the courseplay control menu. I'm not sure if this is intended or not as the one for drive course/stop driver does work when on other menus.

**Comment by JakobTischler** [comment]
What do you mean with "control menu"? When the hud is open? When the hud is open and on a certain page? Please clarify.

**Comment by Voidheartd** [comment]
When it is on the "courseplay control" page is the only time the keybinding works. It doesn't work if the hud is closed or on another page.

**Comment by JakobTischler** [comment]
Uhm ... UHM ... I totally can not for the life of me reproduce this. I use CTRL+KP7 all the time, no matter what page or even if the hud is displayed. This is also the first time I've heard anyone mention it wouldn't work. Any log information?

**Comment by Voidheartd** [comment]
Not ctrl+7. That is drive course/stop driver which does work as I mentioned. I am talking about ctrl+9 which is drive now.

**Comment by JakobTischler** [comment]
Aaaaah, now I get it. Fix will come shortly.

**Comment by Voidheartd** [comment]
Drive now (ctrl+9) keybind no longer working even on courseplay control page with latest files.

**Comment by JakobTischler** [comment]
Try again with the latest commit version.

**Comment by Voidheartd** [comment]
Confirming that it now works with latest commit
