### ISSUE TITLE
Faster tractor with weight ends up in path of combine after unloading

### ISSUE THREAD

**Issue by Voidheartd** [netjungle/courseplay#87]
So I upgraded one of my unloading tractors to the Lamborghini R6.125 with the SIGA DUO, SRB3-35 trailer, and a 2kg weight, and I've noticed that it now stops too close to the crop after unloading while driving on the harvested field (does not occur when unloading while driving over the crops). 

It appears that it's caused by having any weight on the front at all. I even tried with just a 1kg weight (which doesn't allow for full speed) and it happens less but still occurs. Obviously, not having any front weight defeats the purpose of having a faster tractor, since it then goes slower than a slower tractor would. Shape of the weight has no effect either as the tractor is so close the wheels are often what stops the combine.

Steps:
1. Tractor moves to unload combine
2. Combine and tractor reach end of field while unloading (whether combine is there first does not matter) and tractor is sitting on harvested portion of field
3. Unloading completes and tractor moves to stop near the unharvested crops, but goes too far forward, causing combine to be blocked

![fsScreen_2013_02_24_16_56_23](https://f.cloud.github.com/assets/3398909/190126/86bb9c8c-7ecd-11e2-99ed-311488c53f16.jpg)

**Comment by webagencys** [comment]
Hi
 You are using (SpeedLimiter & Operating Hours) Mod I think you incress turning speed on CP .In Image you uploaded i see (level1 - 100%)  so you changed turning speed in CP use Turning speed 7 to 15 so it works Great
i am using CP more than 400 Hours i am not getting this problem

**Comment by Voidheartd** [comment]
I don't think the tractor is even getting up that fast before it has to stop, but I will check during my next harvest. It seems to be more of an issue with the weight of the trailer and front weight preventing a quick enough stop, since the tractor slams on the brake just as it reaches the position.

**Comment by webagencys** [comment]
@Voidheartd 
When you Downloaded The CP? If you downloaded Cp Before 12 Days i Recommend you to download Because CP have good Updates For This Problem Before 11 Days ,Ofter i updated the cp i never get this prob in my game so try it

**Comment by Voidheartd** [comment]
The courseplay I am using is from 15 hours ago. I will update it before next harvest but I don't see any changes in that time period that would affect this.
