### ISSUE TITLE
Request: Remember manually assigned combines

### ISSUE THREAD

**Issue by Voidheartd** [netjungle/courseplay#89]
This is regarding the settings on the manage combine page of the hud.

The automatic assignment is nice, but I've found it easier to use manual assignment and have the tractor sit off the field so it doesn't have to be moved for seeding.

If possible it would be nice if the combine set in "choose combine" would be saved for that tractor, and possibly the "find combine" setting as well.

**Comment by JakobTischler** [comment]
This won't be possible. The list of combines for us basically is a list of IDs. These are valid for the current game session, but will change the next time you start the game. Hence, saving the current ones will have the result of having no combine or maybe a false one assigned.
