### ISSUE TITLE
Tractor with frontloader doesn´t go with the courseplay path, if that tractor is selected (for example Fendt 724).

### ISSUE THREAD

**Issue by tadej14789** [netjungle/courseplay#90]
Tractor, which can attach frontloader, goes with the courseplay path only its self, but if that tractor is selected, it doesn´t go, other words you can steer it even if the courseplay is activated.

**Comment by JakobTischler** [comment]
The very last part of your statement (ability to steer) sounds a lot like a manual ignition problem - which has been fixed in https://github.com/netjungle/courseplay/commit/b8a72084b9e3983527a5de9d64329f9740543b42 - please download the latest version.

**Comment by tadej14789** [comment]
JakobTischler, first I would like to thank You for Your respond, but if You mean the latest version on this site, I allready did it. I have also tried to download some other tractors, but problem is the same

**Comment by tadej14789** [comment]
JakobTischler, first I would like to thank You for Your respond, but if You mean the latest version on this site, I allready did it. I have also tried to download some other tractors, but problem is the same.

I will try to do it without steering wheel.

**Comment by JakobTischler** [comment]
Have you tried removing _all_ other mods except for courseplay and that _one_ tractor? It might be a mod conflict.
(Although to me it _still_ sounds like a manual ignition problem).

**Comment by tadej14789** [comment]
Thank You JakobTischler again. It is manualignition problem I fixed the problem. I deleted manual ignition scripts from modDesc specilizations.

I would just like to ask You if I did it right, and downloaded courseplay master zip file from this site?

Thank You for Your answer in advance.
