### ISSUE TITLE
Forage wagon completes field course rather than driving straight

### ISSUE THREAD

**Issue by gibson89** [netjungle/courseplay#93]
When the forage wagon fills rather than the tractor driving straight to the end of the field it continues to drive the fieldcourse until it gets to the last point before driving the unload course

**Comment by ThomasGaertner** [comment]
please try to replicate it with the latest version and report

THANKS

**Comment by gibson89** [comment]
appears it was a conflict with a mod just tried it on a clean game and it seems to be working fine, sorry for your trouble
