### ISSUE TITLE
At end of Crossing point equipment goes on straight line to start point in DrivingHelper

### ISSUE THREAD

**Issue by ghost** [netjungle/courseplay#97]
I set up a single crosspoint going from the farm to the mill.  I set up individual loading courses for each fruit type.  When loading courses it will go and load then off to the mill.   When it returns it will slow down at the endpoint for the mill course then go on a straight line to the reload point.  This is on an angle from the mill endpoint causing the equipment to run into the silo towers.  It does not line up with the silo entry.

**Comment by Satissis** [comment]
They don't look here anymore. The repository have moved here:
https://github.com/Courseplay/courseplay

So post it there instead.
